import _ from 'lodash';	
export default function($scope, wtdFactory, $filter){

    let params = {
        createHasInput: false
        //isChecked: false
        
    };	

    $scope.date = new Date();
    $scope.date = Date.now();
    //console.log($scope.date);
    //console.log(wtdFactory.createTask);

	//$scope.wtds = [
	//	{
	//		task : 'do dishes',
	//		isCompleted : false,
	//		isEditing : false
	//	},
	//	{
	//		task: 'walk the dog',
	//		isCompleted :  true, 
	//		isEditing : false
	//	}
	//];
	//wtdFactory2.logs();

	$scope.load = function () {
        alert("load event detected!");
    }

	$filter('wtdFilter')();

	$scope.onGenReport = wtd => {

		var pm = ["Abhijeet Murudkar",
					"ABHISHEK RAJ",
					"Abhishek Sharma (Service Delivery)",
					"Adinath Bankar",
					"Ajay Bhore",
					"AKASH SHINDE3",
					"AKSHAY KAVATHEKAR",
					"AKSHAY MASARKAR",
					"Ameya Vaidya",
					"AMI BHUVA",
					"AMIT AMBRE",
					"Amit Ghosh",
					"Amit Ghosh (PM)",
					"AMIT MANE",
					"Amit Shardule",
					"Amit Verma",
					"Amod Sane",
					"Amol Bhoite",
					"Amol Dhage",
					"Anilkumar Kn",
					"Anirban Chakraborty",
					"Ankur Goyal",
					"ANSHUL GUPTA2",
					"Anu Arora",
					"Anuj Gupta",
					"ANURAG NIRMAL",
					"Anurag Singh",
					"Anuranjan Jyoti",
					"APURVA SHAHANE",
					"Arora Ajay",
					"Ayyappillai P",
					"BALAKRISHNAN YADHAVAR",
					"BHUSHAN GAIKWAD",
					"Bijoy Thomas",
					"Blanca Ortanez",
					"Brad Allen",
					"Calla Teo",
					"CHANDRASHEKHAR TIWARI",
					"Chetan Sharma",
					"Christopher Limon",
					"Daneshvar D",
					"Dattaprasad Khanolkar",
					"DEBAJYOTI DAS2",
					"Deepak Bhatt",
					"Deepak Shukla",
					"DEVANAND MAROTI HONRAO",
					"Dipak Kumar",
					"Enrique Sellem",
					"Florian Bonvissuto",
					"Gajraj Thind",
					"HANUMAN REGAR",
					"Haresh Jarkani",
					"Hari Sharma",
					"Harry Cheema",
					"HARSHAL SHINDE2",
					"Hemant Samant",
					"Hitendra Mathur",
					"Indrajeet Ghosh",
					"Jaykesh Sevak",
					"Jeevan Nair",
					"JINAL SHAH",
					"Jitin Pagdhare",
					"Jyoti Rawat",
					"K Rajesh",
					"Kairav Mody",
					"Kalaivani Swamynathan",
					"Kalaivani Swamynathan",
					"Kamil Benadjaoud",
					"Karan Singh",
					"KATHIRAVAN PANDIAN",
					"Kavin Domadia",
					"Krishna Murthy Bandaru",
					"Kumar Vinay",
					"Kunal Roy",
					"Lokesh.Sukumar",
					"Majumdar Anirban",
					"MANIKANDAN UNNIKRISHNAN",
					"Manish Mishra(ASD)",
					"Manoj Bhagwat",
					"Manoj Mishra2",
					"Manoranjan Tiwari",
					"Marco Dosch",
					"Maulik Vyas",
					"Maxime Schneider",
					"MAYUR BABAR",
					"Mayuresh Wagle",
					"MEENAKSHI CHAUDHARY",
					"MEENAKSHI CHAUDHARY",
					"Mohammed Ashfaq",
					"MONISH PATEL",
					"Mukesh Babu K",
					"MUKESH YADAV",
					"Nandi DB",
					"NARESH SONAWANE",
					"NAYAN KOLTE",
					"Neha Saini",
					"Neha Thakur",
					"NIKHIL CHAVAN",
					"Nikhil Warang",
					"Nikunj Gala",
					"Nilesh Indulkar",
					"Nilesh M Patil",
					"Nilesh Naik2",
					"Nilesh Vishe",
					"Olivier Goncalves",
					"Pankaj Kumbhar",
					"Paresh Kumthekar",
					"Paul Bennett",
					"Ponnalagu S",
					"POONAM JAGTAP",
					"Prasenjit Podder",
					"Prashant Pai",
					"Prashant Sonawane",
					"Prashant Srivastava",
					"PRATEEK TIWARI",
					"Praveen Tiwari",
					"Priyal Dabre",
					"Raghavendra Ramdurgkar",
					"Rahul R Pai",
					"Rajeev Sharma",
					"Rajendra Bhikule",
					"Rajib Debnath",
					"Rakesh Salve",
					"Ram Ganga",
					"RAMAMURTHY V",
					"ramesh.maguluri",
					"Ravindra Kale",
					"Revatee Bande",
					"Robert Mathias",
					"Rohan Barmukh2",
					"Rohan Goyal",
					"ROSHANI GAROLE",
					"Ruchi Singh",
					"Saaj Miah",
					"Sabana Bee",
					"Sachin Chavan2",
					"Sachin Shingte",
					"Sameer Chitnis",
					"Sameer Shigwan",
					"Samir Sanas",
					"Sanckar Pathmanathan",
					"Sandeep Barpute",
					"SANDEEP DANGE",
					"SANDEEP DESHMUKH",
					"Sandesh Mankar",
					"SANJAY AKRE",
					"Sankalp Shah",
					"Santiago Epstein",
					"SANTOSH ADAGALE",
					"Satish Gaikwad",
					"SEEMA VARMA",
					"Senthil kumar M (MSK)",
					"SHAIKH MUSTHAQEEM",
					"Shailendra Baghel",
					"Shankar S Shukla",
					"SHANTANU MUKHERJEE2",
					"SHAOXIONG ZHENG",
					"Shipra Sharma",
					"SHOBHA THORAT",
					"Sibo Panda",
					"Sijo Mathew",
					"Smita Choudhary",
					"Smita Phadtare",
					"Snehal Desai",
					"SONALI DOHALE",
					"Sridhar B (PM)",
					"STEPHEN LIM",
					"Subir Banerjee",
					"Sumit Jejurikar",
					"Suraj Shekhar",
					"Suresh Nasina",
					"Sushant D Jangam",
					"Sushil Kale",
					"SUVARNA SHIRKE",
					"Tatiana Zbarsky",
					"Tito Mukherjee",
					"Tony Dormio",
					"Umamahesh K",
					"UMASHANKAR VENKATESH",
					"Umed kaule",
					"Varun Mehta",
					"Varun Mehta",
					"Varun Singhal",
					"Vijayapradheep Kuppuswamy",
					"VIKAS LOTANKAR",
					"VIKI GANDHI",
					"Vikram Vandhu",
					"VIKRANT MHATRE",
					"Vinay Nagavelly",
					"VINAYA JADHAV2",
					"Virender Kumar",
					"Vishal Advani",
					"VK Rai",
					"Vrunda Ghole",
					"Yogesh Awasthi",
					"Akshay Agnihotri",
					"Chintan Patel",
					"Dhyey Kothari",
					"Amit Singh (SPOT)"];

		var pm_fe = ["Amol Bhoite",
						"Gajraj Thind",
						"VK Rai",
						"Sibo Panda",
						"Paresh Kumthekar",
						"Dipak Kumar",
						"Sachin Shingte",
						"Dipak Kumar",
						"Amol Bhoite",
						"Subir Banerjee",
						"Vishal Advani",
						"Hariharan S",
						"Umamahesh K",
						"Dipak Kumar",
						"Kairav Mody",
						"Anu Arora",
						"Amit Ghosh",
						"Raghavendra Ramdurgkar",
						"VK Rai",
						"Arora Ajay",
						"Ayyappillai P",
						"Snehal Desai",
						"Amol Dhage",
						"Kunal Roy",
						"Deepak Bhatt",
						"Adinath Bankar",
						"Smita Phadtare",
						"Smita Phadtare",
						"Neha Thakur",
						"Hariharan S",
						"Kunal Roy",
						"Kairav Mody",
						"Amol Bhoite",
						"Raghavendra Ramdurgkar",
						"Jaykesh Sevak",
						"Rhys Lancaster",
						"Vishal Advani",
						"Gajraj Thind",
						"Ayyappillai P",
						"Jaykesh Sevak",
						"Jaykesh Sevak",
						"Amit Ghosh",
						"Neha Thakur",
						"Jaykesh Sevak",
						"Amol Dhage",
						"Kairav Mody",
						"Jaykesh Sevak",
						"Rohan Goyal",
						"Maxime Schneider",
						"Hariharan S",
						"Dipak Kumar",
						"Vishal Advani",
						"Maxime Schneider",
						"Maxime Schneider",
						"Neha Thakur",
						"Kairav Mody",
						"Amol Bhoite",
						"Sibo Panda",
						"Hariharan S",
						"Amit Ghosh",
						"VK Rai",
						"Neha Thakur",
						"Nandi DB",
						"Ponnalagu S",
						"VK Rai",
						"Tatiana Zbarsky",
						"Tatiana Zbarsky",
						"Maxime Schneider",
						"Amol Bhoite",
						"RAMAMURTHY V",
						"Smita Phadtare",
						"Sandeep Barpute",
						"Mohammed Ashfaq",
						"Arora Ajay",
						"Mohammed Ashfaq",
						"Ayyappillai P",
						"Ponnalagu S",
						"Jaykesh Sevak",
						"Kairav Mody",
						"Kairav Mody",
						"Gajraj Thind",
						"Maxime Schneider",
						"Smita Phadtare",
						"Rhys Lancaster",
						"Dattaprasad Khanolkar",
						"Kairav Mody",
						"Anu Arora",
						"Anu Arora",
						"Anilkumar Kn",
						"Raghavendra Ramdurgkar",
						"Ponnalagu S",
						"Praveen Tiwari",
						"VK Rai",
						"Kairav Mody",
						"Gajraj Thind",
						"Anu Arora",
						"Amit Ghosh",
						"Subir Banerjee",
						"Kairav Mody",
						"Rohan Goyal",
						"Dipak Kumar",
						"Paresh Kumthekar",
						"Amit Ghosh",
						"Dipak Kumar",
						"Maxime Schneider",
						"Amol Bhoite",
						"Raghavendra Ramdurgkar",
						"Maxime Schneider",
						"Anilkumar Kn",
						"Neha Thakur",
						"VK Rai",
						"Mohammed Ashfaq",
						"Amit Ghosh",
						"Mohammed Ashfaq",
						"Dipak Kumar",
						"Amit Ghosh",
						"Paresh Kumthekar",
						"Arora Ajay",
						"Ponnalagu S",
						"Anu Arora",
						"Snehal Desai",
						"Anilkumar Kn",
						"Sibo Panda",
						"Nandi DB",
						"Amit Ghosh",
						"Mohammed Ashfaq",
						"VK Rai",
						"Kairav Mody",
						"Jaykesh Sevak",
						"Kairav Mody",
						"Jaykesh Sevak",
						"Dipak Kumar",
						"Jaykesh Sevak",
						"Maxime Schneider",
						"Ponnalagu S",
						"Rohan Goyal",
						"Amit Ghosh",
						"Jaykesh Sevak",
						"Maxime Schneider",
						"Paresh Kumthekar",
						"Rohan Goyal",
						"Anilkumar Kn",
						"Dipak Kumar",
						"Sushil Kale",
						"Prasenjit Podder",
						"Subir Banerjee",
						"Rohan Goyal",
						"Maxime Schneider",
						"Snehal Desai",
						"Smita Phadtare",
						"Maxime Schneider",
						"Ponnalagu S",
						"Prasenjit Podder",
						"Ayyappillai P",
						"VK Rai",
						"Praveen Tiwari",
						"Calla Teo",
						"Anu Arora",
						"Neha Thakur",
						"Arora Ajay",
						"Mohammed Ashfaq",
						"Sibo Panda",
						"VK Rai",
						"Raghavendra Ramdurgkar",
						"Paresh Kumthekar",
						"Sandeep Barpute",
						"Vishal Advani",
						"Amit Ghosh",
						"Kairav Mody",
						"Umamahesh K",
						"Sandeep Barpute",
						"Kairav Mody",
						"Raghavendra Ramdurgkar",
						"Subir Banerjee",
						"Hariharan S",
						"Jaykesh Sevak",
						"Brad Allen",
						"Kunal Roy",
						"Nilesh Naik2",
						"Kairav Mody",
						"Tatiana Zbarsky",
						"Tatiana Zbarsky",
						"Prasenjit Podder",
						"Mohammed Ashfaq",
						"Amol Bhoite",
						"Prashant Sonawane",
						"Anu Arora",
						"Sushil Kale",
						"Raghavendra Ramdurgkar",
						"Smita Phadtare",
						"Anu Arora",
						"Rhys Lancaster",
						"Hariharan S",
						"Vishal Advani",
						"Ayyappillai P",
						"Vinay Nagavelly",
						"Vinay Nagavelly",
						"Vinay Nagavelly",
						"Pranay Pratap Singh"];
		var vsd = ["Raghavendra Ramdurgkar",
					"Gajraj Thind",
					"VK Rai",
					"Sibo Panda",
					"Raghavendra Ramdurgkar",
					"Jaykesh Sevak",
					"Amit Ghosh",
					"Jaykesh Sevak",
					"Raghavendra Ramdurgkar",
					"Amit Ghosh",
					"Rhys Lancaster",
					"Hariharan S",
					"Kunal Roy",
					"Jaykesh Sevak",
					"Kairav Mody",
					"Kunal Roy",
					"Amit Ghosh",
					"Raghavendra Ramdurgkar",
					"VK Rai",
					"Arora Ajay",
					"Kunal Roy",
					"Raghavendra Ramdurgkar",
					"VK Rai",
					"Kunal Roy",
					"Jaykesh Sevak",
					"Sibo Panda",
					"Smita Phadtare",
					"Smita Phadtare",
					"Amit Ghosh",
					"Hariharan S",
					"Kunal Roy",
					"Kairav Mody",
					"Raghavendra Ramdurgkar",
					"Raghavendra Ramdurgkar",
					"Jaykesh Sevak",
					"Rhys Lancaster",
					"Rhys Lancaster",
					"Gajraj Thind",
					"Kunal Roy",
					"Jaykesh Sevak",
					"Jaykesh Sevak",
					"Amit Ghosh",
					"Amit Ghosh",
					"Jaykesh Sevak",
					"VK Rai",
					"Kairav Mody",
					"Jaykesh Sevak",
					"Jaykesh Sevak",
					"Rhys Lancaster",
					"Hariharan S",
					"Jaykesh Sevak",
					"Rhys Lancaster",
					"Rhys Lancaster",
					"Rhys Lancaster",
					"Amit Ghosh",
					"Kairav Mody",
					"Raghavendra Ramdurgkar",
					"Sibo Panda",
					"Hariharan S",
					"Amit Ghosh",
					"VK Rai",
					"Amit Ghosh",
					"VK Rai",
					"Anilkumar Kn",
					"Kairav Mody",
					"Tatiana Zbarsky",
					"Tatiana Zbarsky",
					"Rhys Lancaster",
					"Raghavendra Ramdurgkar",
					"Amit Ghosh",
					"Smita Phadtare",
					"Anilkumar Kn",
					"Anilkumar Kn",
					"Arora Ajay",
					"Anilkumar Kn",
					"Kunal Roy",
					"Anilkumar Kn",
					"Jaykesh Sevak",
					"Kairav Mody",
					"Kairav Mody",
					"Gajraj Thind",
					"Rhys Lancaster",
					"Smita Phadtare",
					"Rhys Lancaster",
					"Amit Ghosh",
					"Kairav Mody",
					"Kunal Roy",
					"Kunal Roy",
					"Anilkumar Kn",
					"Raghavendra Ramdurgkar",
					"Anilkumar Kn",
					"Amit Ghosh",
					"VK Rai",
					"Kairav Mody",
					"Gajraj Thind",
					"Kunal Roy",
					"Amit Ghosh",
					"Amit Ghosh",
					"Kairav Mody",
					"Jaykesh Sevak",
					"Jaykesh Sevak",
					"Raghavendra Ramdurgkar",
					"Amit Ghosh",
					"Jaykesh Sevak",
					"Rhys Lancaster",
					"Raghavendra Ramdurgkar",
					"Raghavendra Ramdurgkar",
					"Rhys Lancaster",
					"Anilkumar Kn",
					"Amit Ghosh",
					"VK Rai",
					"Anilkumar Kn",
					"Amit Ghosh",
					"Anilkumar Kn",
					"Jaykesh Sevak",
					"Amit Ghosh",
					"Raghavendra Ramdurgkar",
					"Arora Ajay",
					"Anilkumar Kn",
					"Kunal Roy",
					"Raghavendra Ramdurgkar",
					"Anilkumar Kn",
					"Sibo Panda",
					"VK Rai",
					"Amit Ghosh",
					"Anilkumar Kn",
					"Ravindra Kale",
					"Kairav Mody",
					"Jaykesh Sevak",
					"Kairav Mody",
					"Jaykesh Sevak",
					"Jaykesh Sevak",
					"Jaykesh Sevak",
					"Rhys Lancaster",
					"Anilkumar Kn",
					"Jaykesh Sevak",
					"Amit Ghosh",
					"Jaykesh Sevak",
					"Rhys Lancaster",
					"Raghavendra Ramdurgkar",
					"Jaykesh Sevak",
					"Anilkumar Kn",
					"Jaykesh Sevak",
					"Raghavendra Ramdurgkar",
					"VK Rai",
					"Amit Ghosh",
					"Jaykesh Sevak",
					"Rhys Lancaster",
					"Raghavendra Ramdurgkar",
					"Smita Phadtare",
					"Rhys Lancaster",
					"Anilkumar Kn",
					"Amit Ghosh",
					"Kunal Roy",
					"VK Rai",
					"Amit Ghosh",
					"Rhys Lancaster",
					"Kunal Roy",
					"Amit Ghosh",
					"Arora Ajay",
					"Anilkumar Kn",
					"Sibo Panda",
					"Smita Phadtare",
					"Raghavendra Ramdurgkar",
					"Raghavendra Ramdurgkar",
					"Anilkumar Kn",
					"Rhys Lancaster",
					"Amit Ghosh",
					"Kairav Mody",
					"Kunal Roy",
					"Anilkumar Kn",
					"Kairav Mody",
					"Raghavendra Ramdurgkar",
					"Amit Ghosh",
					"Hariharan S",
					"Jaykesh Sevak",
					"Rhys Lancaster",
					"Kunal Roy",
					"Amit Ghosh",
					"Kairav Mody",
					"Tatiana Zbarsky",
					"Tatiana Zbarsky",
					"VK Rai",
					"Anilkumar Kn",
					"Raghavendra Ramdurgkar",
					"Amit Ghosh",
					"Kunal Roy",
					"Raghavendra Ramdurgkar",
					"Raghavendra Ramdurgkar",
					"Smita Phadtare",
					"Kunal Roy",
					"Rhys Lancaster",
					"Hariharan S",
					"Rhys Lancaster",
					"Kunal Roy",
					"Raghavendra Ramdurgkar",
					"Raghavendra Ramdurgkar",
					"Raghavendra Ramdurgkar",
					"Pravesh Bhardwaj"];
		

		for(var i=0;i<199;i++) {
			if(wtd.program_manager == pm[i]){
				wtd.pm_first_level_escalation = pm_fe[i];
				wtd.vsd_mapping = vsd[i];
			}
		}

		var date2 = $scope.toTimeStamp(wtd.e2e_testing_date);
		var date1 = $scope.toTimeStamp(wtd.inbasket_date);
		
		//wtd.TAT = "NA";

		if((wtd.e2e_testing_date!=undefined)){
    			wtd.TAT = (date2-date1)/86400000;
    			wtd.pm_TAT = ($scope.date - date2)/86400000;
    			//wtd.pm_TAT = $scope.date;
    	}
    	else{
    		wtd.TAT = 0;
    		wtd.pm_TAT = 0;
    	}


    	if(wtd.TAT<=5){
    		wtd.TAT_status = "Within TAT";
    	}
    	else{
    		wtd.TAT_status = "Outside TAT";
    	}


    		



	}

	$scope.toTimeStamp = function(date) {
	if(date == undefined){return 0;}
	else {
	    var dateSplitted = String(date).split('-'); // date must be in DD-MM-YYYY format
	    var formattedDate = dateSplitted[1]+'/'+ String(dateSplitted[2]).split('T')[0] +'/'+dateSplitted[0];
	    return new Date(formattedDate).getTime();
	}
  };

	wtdFactory.getTasks($scope);

	$scope.onCompletedClick = wtd => {
		wtd.isCompleted=!wtd.isCompleted;
	};

	
	$scope.onEditClick = wtd => {
		wtd.isEditing = true;
		wtd.updatedTask1 = wtd.tiger_id;
		wtd.updatedTask2 = wtd.viznetm6id;
		wtd.updatedTask3 =	wtd.gam_id;
		wtd.updatedTask4 = wtd.mrc_converted;
		wtd.updatedTask5 = wtd.nrc_converted;
		wtd.updatedTask6 = wtd.sales_region;
		wtd.updatedTask7 =	wtd.customer_name;
		wtd.updatedTask8 = wtd.program_manager;
		wtd.updatedTask9 = wtd.provisioner_name;
		wtd.updatedTask10 = wtd.inbasket_date;
		wtd.updatedTask11 = wtd.wtd_owner_name;
		wtd.updatedTask12 = wtd.service_type;
		wtd.updatedTask13 = wtd.e2e_testing_date;
		wtd.updatedTask14 = wtd.turn_up_date;
		wtd.updatedTask15 = wtd.activation_date;
		wtd.updatedTask16 = wtd.activity_progress_log;
		wtd.updatedTask17 = wtd.current_dependency;
		wtd.updatedTask18 = wtd.program_manager_input;
		wtd.updatedTask19 = wtd.tiger_status;
		wtd.updatedTask20 = wtd.viznetm6status;
		wtd.updatedTask21 = wtd.team_status;

		

	};

	$scope.onCancelClick = wtd => {
		wtd.isEditing = false;
	};

	const { createTask, updateTask, deleteTask, watchCreateTaskInput} = wtdFactory;



	$scope.createTask = _.partial(createTask, $scope , params);

	$scope.updateTask = _.partial(updateTask, $scope); 

	$scope.deleteTask = _.partial(deleteTask, $scope);

	$scope.$watch('createTaskInput', _.partial(watchCreateTaskInput, params, $scope));

	//wtdFilter.dateFilter;
	$scope.isCrammerChecked = true;
	$scope.isViznetChecked = true;
	$scope.isM6Checked = true;



}